### PR TITLE
[sdk] update to Gecko SDK 4.3.0

### PR DESCRIPTION
**Pull request by lmnotran**
- Add `efr32-platform-utils` target, allowing for efr32-specific platform utils to override default platform utils

### CODE REVIEW

**Review by romacdon — APPROVED** [review]
LGTM

**Review by hemanth-silabs — APPROVED** [review]
LGTM 👍

**Review by suveshpratapa — APPROVED** [review]
LGTM

**Review by parag-silabs — APPROVED** [review]
LGTM 👍

**Review by bertoldi-silabs — APPROVED** [review]

**Comment by lmnotran** [comment]
Hi @jwhui can you review this please?

**Review by jwhui — APPROVED** [review]

**Pull request merged**
