### PR TITLE
[alarm] fix bug when `OPENTHREAD_CONFIG_UPTIME_ENABLE` is enabled

### PR DESCRIPTION
**Pull request by lmnotran**

### CODE REVIEW

**Review by hemanth-silabs — APPROVED** [review]
LGTM 👍

**Review by suveshpratapa — APPROVED** [review]
LGTM

**Comment by lmnotran** [comment]
@jwhui could you review this please?

**Comment by lmnotran** [comment]
Sorry, I actually have one more change to make.

**Comment by lmnotran** [comment]
@jwhui I finished making the change. Please review when able

**Review by jwhui — APPROVED** [review]

**Pull request merged**
