### PR TITLE
[crypto] disable PSA crypto in `mbedtls_autogen_config.h`

### PR DESCRIPTION
**Pull request by lmnotran**
PSA Crypto support is still in review
- https://github.com/openthread/openthread/pull/6862

Having `MBEDTLS_USE_PSA_CRYPTO` defined is causing a `Join failed [Security]` failure when trying to commission a new node because PSA crypto isn't fully supported yet. This PR removes the use of PSA crypto in mbedtls

The failure occurs during the "Connecting" state of the joining process. Mbedtls will fail somewhere during the DTLS session establishment with `MBEDTLS_ERR_SSL_HW_ACCEL_FAILED`

### CODE REVIEW

**Review by romacdon — APPROVED** [review]
LGTM

**Review by hemanth-silabs — APPROVED** [review]
LGTM

**Comment by lmnotran** [comment]
@jwhui Could you merge this PR?

**Comment by jwhui** [comment]
> @jwhui Could you merge this PR?

Sure, I was waiting on @schinchani since you tagged him for review. But I can merge now.

**Review by jwhui — APPROVED** [review]

**Pull request merged**
