### PR TITLE
[openthread] revert to `5cab15840df7dddd9d2578106bde3067ad45bbae`

### PR DESCRIPTION
**Pull request by lmnotran**
GSDK 4.3.2 does not support PBKDF2 key generation using PSA, which is causing problems when running the `pskc -p` CLI command.

```
> pskc -p 466D5A00000000000000000000000001
Error 27: NotCapable
>
```

This commit reverts the `openthread` submodule to before https://github.com/openthread/openthread/pull/9655

GSDK 4.4.0 will be released soon, which will have support for PBKDF2 key generation using PSA. After ot-efr32 is updated to use GSDK 4.4.0, we will be able to resume regular updates to the `openthread` submodule

@jwhui Can you disable dependabot updates in the meantime?

### CODE REVIEW

**Review by romacdon — COMMENTED** [review]
LGTM

**Review by romacdon — APPROVED** [review]

**Comment by hemanth-silabs** [comment]
LGTM 👍

**Comment by lmnotran** [comment]
@jwhui could you review this when you get a chance, please?

**Review by jwhui — APPROVED** [review]

**Comment by jwhui** [comment]
> @jwhui Can you disable dependabot updates in the meantime?

I plan to leave dependabot on for now, just so that we can continue to get build checks against `ot-efr32`. I won't merge them until you say to resume merging.

**Comment by lmnotran** [comment]
Sounds good. Thanks @jwhui !

**Pull request merged**
