### PR TITLE
[sdk] update to Gecko SDK 4.2.3

### PR DESCRIPTION
**Pull request by lmnotran**
This updates the gecko_sdk submodule to `4.2.3` and also updates the PAL in `src/src`

It also pulls in recent changes that add ECDSA support to `crypto.c`

### CODE REVIEW

**Comment by romacdon** [comment]
@lmnotran in general this looks ok but I'm curious why there are so differences between files in this PR and the same files in the GSDK PAL.

**Review by romacdon — APPROVED** [review]

**Comment by hemanth-silabs** [comment]
> @lmnotran in general this looks ok but I'm curious why there are so differences between files in this PR and the same files in the GSDK PAL.

@romacdon crypto.c changes are related to ECDSA updates and standardizing return values. And radio.c changes are related mainly to multi buffer updates. I am not sure about diag.c, but I guess it is related to @parag-silabs's updates. These changes are about to go into GSDK

**Review by parag-silabs — APPROVED** [review]
LGTM 👍

**Review by suveshpratapa — APPROVED** [review]
LGTM

**Comment by lmnotran** [comment]
@jwhui could you review this please? Also, thanks for being so responsive with all the reviews!

**Review by jwhui — APPROVED** [review]

**Pull request merged**
