### PR TITLE
[actions] add arm-gcc-{9,10.3} for macOS

### PR DESCRIPTION
**Pull request by lmnotran**
Also, move lint check to new workflow for better organization

### CODE REVIEW

**Comment by lmnotran** [comment]
@jwhui Could you update the required status checks to use the new job names?

**Review by romacdon — APPROVED** [review]
LGTM

**Review by suveshpratapa — APPROVED** [review]
LGTM

**Review by hemanth-silabs — APPROVED** [review]
LGTM 👍

**Review by jwhui — APPROVED** [review]

**Pull request merged**
