### PR TITLE
dont use gnu specific grep

### PR DESCRIPTION
**Pull request by brian-level**
grep -oP is specific to GNU versions of grep which aren't (any longer) used on Mac/OSX platforms.  The use in scripts is a bit overkill for just getting a token. This replaces grep with bash-native parsing

### CODE REVIEW

**Comment by lmnotran** [comment]
Hi @brian-level ! Thanks for submitting the PR!

Theoretically, you shouldn't have run into this issue if you ran `./script/bootstrap` on your system [since it installs GNU grep](https://github.com/openthread/ot-efr32/blob/0604843fabbac866594c6b23e0d2c5062e1ad6e3/script/bootstrap#L83). Every system is different though, so maybe I missed something. Either way, replacing `-oP` with bash-native parsing is an improvement. Could you remove [`grep`](https://github.com/openthread/ot-efr32/blob/0604843fabbac866594c6b23e0d2c5062e1ad6e3/script/bootstrap#L83) from `script/bootstrap` in this PR as well?

**Comment by lmnotran** [comment]
Also, please make sure you sign the CLA

**Review by lmnotran — CHANGES_REQUESTED** [review]
Hi @brian-level ! Thanks for submitting the PR!

Theoretically, you shouldn't have run into this issue if you ran ./script/bootstrap on your system [since it installs GNU grep](https://github.com/openthread/ot-efr32/blob/0604843fabbac866594c6b23e0d2c5062e1ad6e3/script/bootstrap#L83). Every system is different though, so maybe I missed something. Either way, replacing -oP with bash-native parsing is an improvement. Could you remove [grep](https://github.com/openthread/ot-efr32/blob/0604843fabbac866594c6b23e0d2c5062e1ad6e3/script/bootstrap#L83) from script/bootstrap in this PR as well?

Also, please sign the CLA.

**Comment by brian-level** [comment]
> Hi @brian-level ! Thanks for submitting the PR!
> 
> Theoretically, you shouldn't have run into this issue if you ran ./script/bootstrap on your system [since it installs GNU grep](https://github.com/openthread/ot-efr32/blob/0604843fabbac866594c6b23e0d2c5062e1ad6e3/script/bootstrap#L83). Every system is different though, so maybe I missed something. Either way, replacing -oP with bash-native parsing is an improvement. Could you remove [grep](https://github.com/openthread/ot-efr32/blob/0604843fabbac866594c6b23e0d2c5062e1ad6e3/script/bootstrap#L83) from script/bootstrap in this PR as well?
> 
> Also, please sign the CLA.

CLA I had signed earlier for a PR to openthread.  Maybe it'll apply here?

Question: in "openthread/scripts/check-api-version" it seems like the line 59

  `  [[ $(wc -l <"${OT_VERSIONS_FILE}") == 2 ]] || die 'Multiple OPENTHREAD_API_VERSION definitions found!'
`

Will flag the normal case since the grep looks for [-+]#define so will have 2 lines?  I think that == should be a != ?

**Comment by jwhui** [comment]
> CLA I had signed earlier for a PR to openthread. Maybe it'll apply here?

@brian-level , yes it applies here as well. Thanks.

**Comment by brian-level** [comment]
> Question: in "openthread/scripts/check-api-version" it seems like the line 59
> 
> ` [[ $(wc -l <"${OT_VERSIONS_FILE}") == 2 ]] || die 'Multiple OPENTHREAD_API_VERSION definitions found!'`
> 
> Will flag the normal case since the grep looks for [-+]#define so will have 2 lines? I think that == should be a != ?

I think I need to leave grep in the bootstrap.  There could be cases where people on non-Macs need it, or on Macs if they haven't installed the xcode commandline tools perhaps. 

The issue is that newer mac os doesnt allow even sudo access to /usr/bin and other places where things like grep are installed by Xcode which override brew apps.  I have this issue with cmake as well.  Using simpler greps is better IMHO anyway but there was really nothing wrong with the scripts except for Apple deciding to be Apple

**Pull request closed without merging**
